### ISSUE TITLE
incompatible with M2.4.4 which requires php8.1

### ISSUE THREAD

**Issue by n2diving-net** [rohitkundale/order-comment#17] opened 2022-04-14 11:06 UTC
$ php bin/magento --version
Magento CLI 2.4.4
$ php -v
PHP 8.1.4 (cli) (built: Apr 12 2022 11:12:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies

$ composer require --update-no-dev rohitkundale/order-comment

  [InvalidArgumentException]
  Package rohitkundale/order-comment has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - rohitkundale/order-comment 2.0.4 requires php ~5.6.0|~7.0.0|~7.1.0|~7.2.0|~7.3.0|~7.4.0 which does not match your installed version 8.1.4.

**Comment by rohitkundale** [comment] 2022-04-23 09:28
@n2diving-dgx
Thanks for reporting the issue.
The issue is fixed in lastest release https://github.com/rohitkundale/order-comment/releases/tag/2.0.5

**Closed as completed by rohitkundale** 2022-04-23 09:28 UTC
